version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: attbancojava
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bancoaulajava
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha_rede

volumes:
  mysql_data:
    driver: local

networks:
  minha_rede:
    driver: bridge
